name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix: # multiple configurations to run the actions.....
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include: # include combinations from matrix strategy
          - node-version: 18 
            operating-system: ubuntu-latest
        exclude:  # exclude combinations from matrix strategy
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout#@v3
      - name: Install Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      